#ifndef BLUC_MODE_H
#define BLUC_MODE_H

#include "driver/gpio.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_ota_ops.h"
#include "esp_partition.h"
#include "esp_system.h"

#ifdef CONFIG_BLUCONTROL_MODE_LENGTH
    #define MODE_LENGTH CONFIG_BLUCONTROL_MODE_LENGTH
#else
    #define MODE_LENGTH 1
#endif

#ifdef CONFIG_BLUCONTROL_MODE1_LED_GPIO
    #define MODE1_LED_PIN CONFIG_BLUCONTROL_MODE1_LED_GPIO
#else
    #define MODE1_LED_PIN -1
#endif

#ifdef CONFIG_BLUCONTROL_MODE2_LED_GPIO
    #define MODE2_LED_PIN CONFIG_BLUCONTROL_MODE2_LED_GPIO
#endif

#ifdef CONFIG_BLUCONTROL_MODE3_LED_GPIO
    #define MODE3_LED_PIN CONFIG_BLUCONTROL_MODE3_LED_GPIO
#endif

#ifdef CONFIG_BLUCONTROL_MODE4_LED_GPIO
    #define MODE4_LED_PIN CONFIG_BLUCONTROL_MODE4_LED_GPIO
#endif

#ifdef CONFIG_BLUCONTROL_MODE5_LED_GPIO
    #define MODE5_LED_PIN CONFIG_BLUCONTROL_MODE5_LED_GPIO
#endif

#ifdef CONFIG_BLUCONTROL_MODE6_LED_GPIO
    #define MODE6_LED_PIN CONFIG_BLUCONTROL_MODE6_LED_GPIO
#endif

#ifdef CONFIG_BLUCONTROL_MODE7_LED_GPIO
    #define MODE7_LED_PIN CONFIG_BLUCONTROL_MODE7_LED_GPIO
#endif

#ifdef CONFIG_BLUCONTROL_MODE8_LED_GPIO
    #define MODE8_LED_PIN CONFIG_BLUCONTROL_MODE8_LED_GPIO
#endif

#ifdef CONFIG_BLUCONTROL_MODE9_LED_GPIO
    #define MODE9_LED_PIN CONFIG_BLUCONTROL_MODE9_LED_GPIO
#endif

#ifdef CONFIG_BLUCONTROL_MODE10_LED_GPIO
    #define MODE10_LED_PIN CONFIG_BLUCONTROL_MODE10_LED_GPIO
#endif


#ifdef CONFIG_BLUCONTROL_SECONDS_FOR_SWITCH_MODE
    #define SECONDS_TO_SWITCH CONFIG_BLUCONTROL_SECONDS_FOR_SWITCH_MODE
#else
    #define SECONDS_TO_SWITCH 5
#endif


#ifdef CONFIG_BLUCONTROL_SWITCH_BUTTONS_LENGTH
    #define SWITCH_BUTTONS_LENGTH CONFIG_BLUCONTROL_SWITCH_BUTTONS_LENGTH
#else
    #define SWITCH_BUTTONS_LENGTH 1
#endif

#ifdef CONFIG_BLUCONTROL_SWITCH_BUTTON1_GPIO
    #define SWITCH_BUTTON1_PIN CONFIG_BLUCONTROL_SWITCH_BUTTON1_GPIO
#else
    #define SWITCH_BUTTON1_PIN -1
#endif

#ifdef CONFIG_BLUCONTROL_SWITCH_BUTTON2_GPIO
    #define SWITCH_BUTTON2_PIN CONFIG_BLUCONTROL_SWITCH_BUTTON2_GPIO
#endif

#ifdef CONFIG_BLUCONTROL_SWITCH_BUTTON3_GPIO
    #define SWITCH_BUTTON3_PIN CONFIG_BLUCONTROL_SWITCH_BUTTON3_GPIO
#endif

#ifdef CONFIG_BLUCONTROL_SWITCH_BUTTON4_GPIO
    #define SWITCH_BUTTON4_PIN CONFIG_BLUCONTROL_SWITCH_BUTTON4_GPIO
#endif

#ifdef CONFIG_BLUCONTROL_LEDS_MODE_HIGH
    #define LED_POWER_ON 1
#else
    #define LED_POWER_ON 0
#endif

// Misc
#ifdef CONFIG_BLUCONTROL_BUTTONS_PRESS_STATE_HIGH
    #define BUTTONS_PRESS_STATE 1
#else
    #define BUTTONS_PRESS_STATE 0
#endif

void blucontrol_mode_init(bool _has_ota);
bool blucontrol_handle_buttons(void);
void blucontrol_switch_mode(void);
void blucontrol_switch_ota_mode(void);

#endif